# Generated by Django 3.2.9 on 2022-03-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortener',
        ),
    ]
