# Generated by Django 3.2.9 on 2022-03-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20220308_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='link',
            name='shortened_link',
        ),
    ]
